--Change script command to MyMDb database...
USE [MyMDb]
GO
--Remove ISO3166 and its assosicated objects...
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ISO3166]') AND type in (N'U'))
	DROP TABLE [dbo].[ISO3166]
GO
--Create the ISO3166 Table...
CREATE TABLE [dbo].[ISO3166](
	[Alpha3] [char](3) NOT NULL,
	[Alpha2] [char](2) NOT NULL,
	[Name] [varchar](80) NOT NULL,
	CONSTRAINT [PK_ISO3166] PRIMARY KEY CLUSTERED 
	(
		[Alpha3] ASC
	)
)
GO
--Create Documentation for the ISO3166 Table...
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ISO 3166 Alpha 3 code for the country' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ISO3166', @level2type=N'COLUMN',@level2name=N'Alpha3'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ISO 3166 Alpha 2 code for the country' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ISO3166', @level2type=N'COLUMN',@level2name=N'Alpha2'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'International (English) name of the country' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ISO3166', @level2type=N'COLUMN',@level2name=N'Name'
EXEC sys.sp_addextendedproperty @name=N'InfoUpdated', @value=N'1/4/2012' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ISO3166'
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'ISO 3166 is the International Standard for country codes and codes for their subdivisions. The purpose of ISO 3166 is to establish internationally recognised codes for the representation of names of countries, territories or areas of geographical interest, and their subdivisions. However, ISO 3166 does not establish the names of countries, only the codes that represent them.
The country names in ISO 3166 come from United Nations sources. New names and codes are added automatically when the United Nations publishes new names in either the Terminology Bulletin Country Names or in the Country and Region Codes for Statistical Use maintained by the United Nations Statistics Divisions. Names for subdivisions are taken from relevant official national information sources.
ISO 3166 was first published in 1974 as a single standard to establish the country codes. It was expanded into three parts in 1997 to include the codes for subdivisions and the codes for names of countries that are no longer in use. Of the three parts, Part 1, ISO 3166-1 is generally used the most often.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ISO3166'
EXEC sys.sp_addextendedproperty @name=N'Author', @value=N'Paw Jershauge' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ISO3166'
EXEC sys.sp_addextendedproperty @name=N'Blog', @value=N'http://PawJershauge.blogspot.com' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ISO3166'
EXEC sys.sp_addextendedproperty @name=N'CodeProject.com', @value=N'http://www.codeproject.com/Members/Paw-Jershauge' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ISO3166'
EXEC sys.sp_addextendedproperty @name=N'Version', @value=N'1.0.0.0', @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ISO3166'
DECLARE @lst as varchar(20)
SET @lst = GETDATE()
EXEC sys.sp_addextendedproperty @name=N'Last Sync Time', @value=@lst, @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ISO3166'
GO
--Create IX_Name Index the ISO3166 Table...
CREATE UNIQUE NONCLUSTERED INDEX [IX_Name] ON [dbo].[ISO3166]
(
	[Name] ASC
)
GO
--Create IX_Alpha2 Index the ISO3166 Table...
CREATE UNIQUE NONCLUSTERED INDEX [IX_Alpha2] ON [dbo].[ISO3166]
(
	[Alpha2] ASC
)
GO
--Insert values into the ISO3166 Table...
INSERT INTO [dbo].[ISO3166] VALUES('ABW','AW','Aruba')
INSERT INTO [dbo].[ISO3166] VALUES('AFG','AF','Afghanistan')
INSERT INTO [dbo].[ISO3166] VALUES('AGO','AO','Angola')
INSERT INTO [dbo].[ISO3166] VALUES('AIA','AI','Anguilla')
INSERT INTO [dbo].[ISO3166] VALUES('ALA','AX','�land Islands')
INSERT INTO [dbo].[ISO3166] VALUES('ALB','AL','Albania')
INSERT INTO [dbo].[ISO3166] VALUES('AND','AD','Andorra')
INSERT INTO [dbo].[ISO3166] VALUES('ANT','AN','Netherlands Antilles')
INSERT INTO [dbo].[ISO3166] VALUES('ARE','AE','United Arab Emirates')
INSERT INTO [dbo].[ISO3166] VALUES('ARG','AR','Argentina')
INSERT INTO [dbo].[ISO3166] VALUES('ARM','AM','Armenia')
INSERT INTO [dbo].[ISO3166] VALUES('ASM','AS','American Samoa')
INSERT INTO [dbo].[ISO3166] VALUES('ATA','AQ','Antarctica')
INSERT INTO [dbo].[ISO3166] VALUES('ATF','TF','French Southern Territories')
INSERT INTO [dbo].[ISO3166] VALUES('ATG','AG','Antigua And Barbuda')
INSERT INTO [dbo].[ISO3166] VALUES('AUS','AU','Australia')
INSERT INTO [dbo].[ISO3166] VALUES('AUT','AT','Austria')
INSERT INTO [dbo].[ISO3166] VALUES('AZE','AZ','Azerbaijan')
INSERT INTO [dbo].[ISO3166] VALUES('BDI','BI','Burundi')
INSERT INTO [dbo].[ISO3166] VALUES('BEL','BE','Belgium')
INSERT INTO [dbo].[ISO3166] VALUES('BEN','BJ','Benin')
INSERT INTO [dbo].[ISO3166] VALUES('BES','BQ','Bonaire, Sint Eustatius And Saba')
INSERT INTO [dbo].[ISO3166] VALUES('BFA','BF','Burkina Faso')
INSERT INTO [dbo].[ISO3166] VALUES('BGD','BD','Bangladesh')
INSERT INTO [dbo].[ISO3166] VALUES('BGR','BG','Bulgaria')
INSERT INTO [dbo].[ISO3166] VALUES('BHR','BH','Bahrain')
INSERT INTO [dbo].[ISO3166] VALUES('BHS','BS','Bahamas')
INSERT INTO [dbo].[ISO3166] VALUES('BIH','BA','Bosnia And Herzegowina')
INSERT INTO [dbo].[ISO3166] VALUES('BLM','BL','Saint Barth�lemy')
INSERT INTO [dbo].[ISO3166] VALUES('BLR','BY','Belarus')
INSERT INTO [dbo].[ISO3166] VALUES('BLZ','BZ','Belize')
INSERT INTO [dbo].[ISO3166] VALUES('BMU','BM','Bermuda')
INSERT INTO [dbo].[ISO3166] VALUES('BOL','BO','Bolivia')
INSERT INTO [dbo].[ISO3166] VALUES('BRA','BR','Brazil')
INSERT INTO [dbo].[ISO3166] VALUES('BRB','BB','Barbados')
INSERT INTO [dbo].[ISO3166] VALUES('BRN','BN','Brunei Darussalam')
INSERT INTO [dbo].[ISO3166] VALUES('BTN','BT','Bhutan')
INSERT INTO [dbo].[ISO3166] VALUES('BVT','BV','Bouvet Island')
INSERT INTO [dbo].[ISO3166] VALUES('BWA','BW','Botswana')
INSERT INTO [dbo].[ISO3166] VALUES('CAF','CF','Central African Republic')
INSERT INTO [dbo].[ISO3166] VALUES('CAN','CA','Canada')
INSERT INTO [dbo].[ISO3166] VALUES('CCK','CC','Cocos (Keeling) Islands')
INSERT INTO [dbo].[ISO3166] VALUES('CHE','CH','Switzerland')
INSERT INTO [dbo].[ISO3166] VALUES('CHL','CL','Chile')
INSERT INTO [dbo].[ISO3166] VALUES('CHN','CN','China')
INSERT INTO [dbo].[ISO3166] VALUES('CIV','CI','Cote D''ivoire')
INSERT INTO [dbo].[ISO3166] VALUES('CMR','CM','Cameroon')
INSERT INTO [dbo].[ISO3166] VALUES('COG','CG','Congo')
INSERT INTO [dbo].[ISO3166] VALUES('COK','CK','Cook Islands')
INSERT INTO [dbo].[ISO3166] VALUES('COL','CO','Colombia')
INSERT INTO [dbo].[ISO3166] VALUES('COM','KM','Comoros')
INSERT INTO [dbo].[ISO3166] VALUES('CPV','CV','Cape Verde')
INSERT INTO [dbo].[ISO3166] VALUES('CRI','CR','Costa Rica')
INSERT INTO [dbo].[ISO3166] VALUES('CUB','CU','Cuba')
INSERT INTO [dbo].[ISO3166] VALUES('CUW','CW','Cura�ao')
INSERT INTO [dbo].[ISO3166] VALUES('CXR','CX','Christmas Island')
INSERT INTO [dbo].[ISO3166] VALUES('CYM','KY','Cayman Islands')
INSERT INTO [dbo].[ISO3166] VALUES('CYP','CY','Cyprus')
INSERT INTO [dbo].[ISO3166] VALUES('CZE','CZ','Czech Republic')
INSERT INTO [dbo].[ISO3166] VALUES('DEU','DE','Germany')
INSERT INTO [dbo].[ISO3166] VALUES('DJI','DJ','Djibouti')
INSERT INTO [dbo].[ISO3166] VALUES('DMA','DM','Dominica')
INSERT INTO [dbo].[ISO3166] VALUES('DNK','DK','Denmark')
INSERT INTO [dbo].[ISO3166] VALUES('DOM','DO','Dominican Republic')
INSERT INTO [dbo].[ISO3166] VALUES('DZA','DZ','Algeria')
INSERT INTO [dbo].[ISO3166] VALUES('ECU','EC','Ecuador')
INSERT INTO [dbo].[ISO3166] VALUES('EGY','EG','Egypt')
INSERT INTO [dbo].[ISO3166] VALUES('ERI','ER','Eritrea')
INSERT INTO [dbo].[ISO3166] VALUES('ESH','EH','Western Sahara')
INSERT INTO [dbo].[ISO3166] VALUES('ESP','ES','Spain')
INSERT INTO [dbo].[ISO3166] VALUES('EST','EE','Estonia')
INSERT INTO [dbo].[ISO3166] VALUES('ETH','ET','Ethiopia')
INSERT INTO [dbo].[ISO3166] VALUES('FIN','FI','Finland')
INSERT INTO [dbo].[ISO3166] VALUES('FJI','FJ','Fiji')
INSERT INTO [dbo].[ISO3166] VALUES('FLK','FK','Falkland Islands (Malvinas)')
INSERT INTO [dbo].[ISO3166] VALUES('FRA','FR','France')
INSERT INTO [dbo].[ISO3166] VALUES('FRO','FO','Faroe Islands')
INSERT INTO [dbo].[ISO3166] VALUES('FSM','FM','Micronesia, Federated States Of')
INSERT INTO [dbo].[ISO3166] VALUES('FXX','FX','France, Metropolitan')
INSERT INTO [dbo].[ISO3166] VALUES('GAB','GA','Gabon')
INSERT INTO [dbo].[ISO3166] VALUES('GBR','GB','United Kingdom')
INSERT INTO [dbo].[ISO3166] VALUES('GEO','GE','Georgia')
INSERT INTO [dbo].[ISO3166] VALUES('GGY','GG','Guernsey')
INSERT INTO [dbo].[ISO3166] VALUES('GHA','GH','Ghana')
INSERT INTO [dbo].[ISO3166] VALUES('GIB','GI','Gibraltar')
INSERT INTO [dbo].[ISO3166] VALUES('GIN','GN','Guinea')
INSERT INTO [dbo].[ISO3166] VALUES('GLP','GP','Guadeloupe')
INSERT INTO [dbo].[ISO3166] VALUES('GMB','GM','Gambia')
INSERT INTO [dbo].[ISO3166] VALUES('GNB','GW','Guinea-Bissau')
INSERT INTO [dbo].[ISO3166] VALUES('GNQ','GQ','Equatorial Guinea')
INSERT INTO [dbo].[ISO3166] VALUES('GRC','GR','Greece')
INSERT INTO [dbo].[ISO3166] VALUES('GRD','GD','Grenada')
INSERT INTO [dbo].[ISO3166] VALUES('GRL','GL','Greenland')
INSERT INTO [dbo].[ISO3166] VALUES('GTM','GT','Guatemala')
INSERT INTO [dbo].[ISO3166] VALUES('GUF','GF','French Guiana')
INSERT INTO [dbo].[ISO3166] VALUES('GUM','GU','Guam')
INSERT INTO [dbo].[ISO3166] VALUES('GUY','GY','Guyana')
INSERT INTO [dbo].[ISO3166] VALUES('HKG','HK','Hong Kong')
INSERT INTO [dbo].[ISO3166] VALUES('HMD','HM','Heard And Mc Donald Islands')
INSERT INTO [dbo].[ISO3166] VALUES('HND','HN','Honduras')
INSERT INTO [dbo].[ISO3166] VALUES('HRV','HR','Croatia (Local Name: Hrvatska)')
INSERT INTO [dbo].[ISO3166] VALUES('HTI','HT','Haiti')
INSERT INTO [dbo].[ISO3166] VALUES('HUN','HU','Hungary')
INSERT INTO [dbo].[ISO3166] VALUES('IDN','ID','Indonesia')
INSERT INTO [dbo].[ISO3166] VALUES('IMN','IM','Isle Of Man')
INSERT INTO [dbo].[ISO3166] VALUES('IND','IN','India')
INSERT INTO [dbo].[ISO3166] VALUES('IOT','IO','British Indian Ocean Territory')
INSERT INTO [dbo].[ISO3166] VALUES('IRL','IE','Ireland')
INSERT INTO [dbo].[ISO3166] VALUES('IRN','IR','Iran (Islamic Republic Of)')
INSERT INTO [dbo].[ISO3166] VALUES('IRQ','IQ','Iraq')
INSERT INTO [dbo].[ISO3166] VALUES('ISL','IS','Iceland')
INSERT INTO [dbo].[ISO3166] VALUES('ISR','IL','Israel')
INSERT INTO [dbo].[ISO3166] VALUES('ITA','IT','Italy')
INSERT INTO [dbo].[ISO3166] VALUES('JAM','JM','Jamaica')
INSERT INTO [dbo].[ISO3166] VALUES('JEY','JE','Jersey')
INSERT INTO [dbo].[ISO3166] VALUES('JOR','JO','Jordan')
INSERT INTO [dbo].[ISO3166] VALUES('JPN','JP','Japan')
INSERT INTO [dbo].[ISO3166] VALUES('KAZ','KZ','Kazakhstan')
INSERT INTO [dbo].[ISO3166] VALUES('KEN','KE','Kenya')
INSERT INTO [dbo].[ISO3166] VALUES('KGZ','KG','Kyrgyzstan')
INSERT INTO [dbo].[ISO3166] VALUES('KHM','KH','Cambodia')
INSERT INTO [dbo].[ISO3166] VALUES('KIR','KI','Kiribati')
INSERT INTO [dbo].[ISO3166] VALUES('KNA','KN','Saint Kitts And Nevis')
INSERT INTO [dbo].[ISO3166] VALUES('KOR','KR','Korea, Republic Of')
INSERT INTO [dbo].[ISO3166] VALUES('KOS','KO','Kosovo')
INSERT INTO [dbo].[ISO3166] VALUES('KWT','KW','Kuwait')
INSERT INTO [dbo].[ISO3166] VALUES('LAO','LA','Lao People''s Democratic Republic')
INSERT INTO [dbo].[ISO3166] VALUES('LBN','LB','Lebanon')
INSERT INTO [dbo].[ISO3166] VALUES('LBR','LR','Liberia')
INSERT INTO [dbo].[ISO3166] VALUES('LBY','LY','Libyan Arab Jamahiriya')
INSERT INTO [dbo].[ISO3166] VALUES('LCA','LC','Saint Lucia')
INSERT INTO [dbo].[ISO3166] VALUES('LIE','LI','Liechtenstein')
INSERT INTO [dbo].[ISO3166] VALUES('LKA','LK','Sri Lanka')
INSERT INTO [dbo].[ISO3166] VALUES('LSO','LS','Lesotho')
INSERT INTO [dbo].[ISO3166] VALUES('LTU','LT','Lithuania')
INSERT INTO [dbo].[ISO3166] VALUES('LUX','LU','Luxembourg')
INSERT INTO [dbo].[ISO3166] VALUES('LVA','LV','Latvia')
INSERT INTO [dbo].[ISO3166] VALUES('MAC','MO','Macau')
INSERT INTO [dbo].[ISO3166] VALUES('MAR','MA','Morocco')
INSERT INTO [dbo].[ISO3166] VALUES('MCO','MC','Monaco')
INSERT INTO [dbo].[ISO3166] VALUES('MDA','MD','Moldova, Republic Of')
INSERT INTO [dbo].[ISO3166] VALUES('MDG','MG','Madagascar')
INSERT INTO [dbo].[ISO3166] VALUES('MDV','MV','Maldives')
INSERT INTO [dbo].[ISO3166] VALUES('MEX','MX','Mexico')
INSERT INTO [dbo].[ISO3166] VALUES('MHL','MH','Marshall Islands')
INSERT INTO [dbo].[ISO3166] VALUES('MKD','MK','Macedonia, The Former Yugoslav Republic Of')
INSERT INTO [dbo].[ISO3166] VALUES('MLI','ML','Mali')
INSERT INTO [dbo].[ISO3166] VALUES('MLT','MT','Malta')
INSERT INTO [dbo].[ISO3166] VALUES('MMR','MM','Myanmar')
INSERT INTO [dbo].[ISO3166] VALUES('MNE','ME','Montenegro')
INSERT INTO [dbo].[ISO3166] VALUES('MNG','MN','Mongolia')
INSERT INTO [dbo].[ISO3166] VALUES('MNP','MP','Northern Mariana Islands')
INSERT INTO [dbo].[ISO3166] VALUES('MOZ','MZ','Mozambique')
INSERT INTO [dbo].[ISO3166] VALUES('MRT','MR','Mauritania')
INSERT INTO [dbo].[ISO3166] VALUES('MSR','MS','Montserrat')
INSERT INTO [dbo].[ISO3166] VALUES('MTQ','MQ','Martinique')
INSERT INTO [dbo].[ISO3166] VALUES('MUS','MU','Mauritius')
INSERT INTO [dbo].[ISO3166] VALUES('MWI','MW','Malawi')
INSERT INTO [dbo].[ISO3166] VALUES('MYS','MY','Malaysia')
INSERT INTO [dbo].[ISO3166] VALUES('MYT','YT','Mayotte')
INSERT INTO [dbo].[ISO3166] VALUES('NAM','NA','Namibia')
INSERT INTO [dbo].[ISO3166] VALUES('NCL','NC','New Caledonia')
INSERT INTO [dbo].[ISO3166] VALUES('NER','NE','Niger')
INSERT INTO [dbo].[ISO3166] VALUES('NFK','NF','Norfolk Island')
INSERT INTO [dbo].[ISO3166] VALUES('NGA','NG','Nigeria')
INSERT INTO [dbo].[ISO3166] VALUES('NIC','NI','Nicaragua')
INSERT INTO [dbo].[ISO3166] VALUES('NIU','NU','Niue')
INSERT INTO [dbo].[ISO3166] VALUES('NLD','NL','Netherlands')
INSERT INTO [dbo].[ISO3166] VALUES('NOR','NO','Norway')
INSERT INTO [dbo].[ISO3166] VALUES('NPL','NP','Nepal')
INSERT INTO [dbo].[ISO3166] VALUES('NRU','NR','Nauru')
INSERT INTO [dbo].[ISO3166] VALUES('NZL','NZ','New Zealand')
INSERT INTO [dbo].[ISO3166] VALUES('OMN','OM','Oman')
INSERT INTO [dbo].[ISO3166] VALUES('PAK','PK','Pakistan')
INSERT INTO [dbo].[ISO3166] VALUES('PAN','PA','Panama')
INSERT INTO [dbo].[ISO3166] VALUES('PCN','PN','Pitcairn')
INSERT INTO [dbo].[ISO3166] VALUES('PER','PE','Peru')
INSERT INTO [dbo].[ISO3166] VALUES('PHL','PH','Philippines')
INSERT INTO [dbo].[ISO3166] VALUES('PLW','PW','Palau')
INSERT INTO [dbo].[ISO3166] VALUES('PNG','PG','Papua New Guinea')
INSERT INTO [dbo].[ISO3166] VALUES('POL','PL','Poland')
INSERT INTO [dbo].[ISO3166] VALUES('PRI','PR','Puerto Rico')
INSERT INTO [dbo].[ISO3166] VALUES('PRK','KP','Korea, Democratic People''s Republic Of')
INSERT INTO [dbo].[ISO3166] VALUES('PRT','PT','Portugal')
INSERT INTO [dbo].[ISO3166] VALUES('PRY','PY','Paraguay')
INSERT INTO [dbo].[ISO3166] VALUES('PSE','PS','Palestine, State Of')
INSERT INTO [dbo].[ISO3166] VALUES('PYF','PF','French Polynesia')
INSERT INTO [dbo].[ISO3166] VALUES('QAT','QA','Qatar')
INSERT INTO [dbo].[ISO3166] VALUES('REU','RE','Reunion')
INSERT INTO [dbo].[ISO3166] VALUES('ROM','RO','Romania')
INSERT INTO [dbo].[ISO3166] VALUES('RUS','RU','Russian Federation')
INSERT INTO [dbo].[ISO3166] VALUES('RWA','RW','Rwanda')
INSERT INTO [dbo].[ISO3166] VALUES('SAU','SA','Saudi Arabia')
INSERT INTO [dbo].[ISO3166] VALUES('SDN','SD','Sudan')
INSERT INTO [dbo].[ISO3166] VALUES('SEN','SN','Senegal')
INSERT INTO [dbo].[ISO3166] VALUES('SGP','SG','Singapore')
INSERT INTO [dbo].[ISO3166] VALUES('SGS','GS','South Georgia And The South Sandwich Islands')
INSERT INTO [dbo].[ISO3166] VALUES('SHN','SH','St. Helena')
INSERT INTO [dbo].[ISO3166] VALUES('SJM','SJ','Svalbard And Jan Mayen Islands')
INSERT INTO [dbo].[ISO3166] VALUES('SLB','SB','Solomon Islands')
INSERT INTO [dbo].[ISO3166] VALUES('SLE','SL','Sierra Leone')
INSERT INTO [dbo].[ISO3166] VALUES('SLV','SV','El Salvador')
INSERT INTO [dbo].[ISO3166] VALUES('SMR','SM','San Marino')
INSERT INTO [dbo].[ISO3166] VALUES('SOM','SO','Somalia')
INSERT INTO [dbo].[ISO3166] VALUES('SPM','PM','St. Pierre And Miquelon')
INSERT INTO [dbo].[ISO3166] VALUES('SRB','RS','Serbia')
INSERT INTO [dbo].[ISO3166] VALUES('SSD','SS','South sudan')
INSERT INTO [dbo].[ISO3166] VALUES('STP','ST','Sao Tome And Principe')
INSERT INTO [dbo].[ISO3166] VALUES('SUR','SR','Suriname')
INSERT INTO [dbo].[ISO3166] VALUES('SVK','SK','Slovakia (Slovak Republic)')
INSERT INTO [dbo].[ISO3166] VALUES('SVN','SI','Slovenia')
INSERT INTO [dbo].[ISO3166] VALUES('SWE','SE','Sweden')
INSERT INTO [dbo].[ISO3166] VALUES('SWZ','SZ','Swaziland')
INSERT INTO [dbo].[ISO3166] VALUES('SXM','SX','Sint Maarten (Dutch Part)')
INSERT INTO [dbo].[ISO3166] VALUES('SYC','SC','Seychelles')
INSERT INTO [dbo].[ISO3166] VALUES('SYR','SY','Syrian Arab Republic')
INSERT INTO [dbo].[ISO3166] VALUES('TCA','TC','Turks And Caicos Islands')
INSERT INTO [dbo].[ISO3166] VALUES('TCD','TD','Chad')
INSERT INTO [dbo].[ISO3166] VALUES('TGO','TG','Togo')
INSERT INTO [dbo].[ISO3166] VALUES('THA','TH','Thailand')
INSERT INTO [dbo].[ISO3166] VALUES('TJK','TJ','Tajikistan')
INSERT INTO [dbo].[ISO3166] VALUES('TKL','TK','Tokelau')
INSERT INTO [dbo].[ISO3166] VALUES('TKM','TM','Turkmenistan')
INSERT INTO [dbo].[ISO3166] VALUES('TMP','TP','East Timor')
INSERT INTO [dbo].[ISO3166] VALUES('TON','TO','Tonga')
INSERT INTO [dbo].[ISO3166] VALUES('TTO','TT','Trinidad And Tobago')
INSERT INTO [dbo].[ISO3166] VALUES('TUN','TN','Tunisia')
INSERT INTO [dbo].[ISO3166] VALUES('TUR','TR','Turkey')
INSERT INTO [dbo].[ISO3166] VALUES('TUV','TV','Tuvalu')
INSERT INTO [dbo].[ISO3166] VALUES('TWN','TW','Taiwan, Province Of China')
INSERT INTO [dbo].[ISO3166] VALUES('TZA','TZ','Tanzania, United Republic Of')
INSERT INTO [dbo].[ISO3166] VALUES('UGA','UG','Uganda')
INSERT INTO [dbo].[ISO3166] VALUES('UKR','UA','Ukraine')
INSERT INTO [dbo].[ISO3166] VALUES('UMI','UM','United States Minor Outlying Islands')
INSERT INTO [dbo].[ISO3166] VALUES('URY','UY','Uruguay')
INSERT INTO [dbo].[ISO3166] VALUES('USA','US','United States')
INSERT INTO [dbo].[ISO3166] VALUES('UZB','UZ','Uzbekistan')
INSERT INTO [dbo].[ISO3166] VALUES('VAT','VA','Vatican City State (Holy See)')
INSERT INTO [dbo].[ISO3166] VALUES('VCT','VC','Saint Vincent And The Grenadines')
INSERT INTO [dbo].[ISO3166] VALUES('VEN','VE','Venezuela')
INSERT INTO [dbo].[ISO3166] VALUES('VGB','VG','Virgin Islands (British)')
INSERT INTO [dbo].[ISO3166] VALUES('VIR','VI','Virgin Islands (U.S.)')
INSERT INTO [dbo].[ISO3166] VALUES('VNM','VN','Viet Nam')
INSERT INTO [dbo].[ISO3166] VALUES('VUT','VU','Vanuatu')
INSERT INTO [dbo].[ISO3166] VALUES('WLF','WF','Wallis And Futuna Islands')
INSERT INTO [dbo].[ISO3166] VALUES('WSM','WS','Samoa')
INSERT INTO [dbo].[ISO3166] VALUES('YEM','YE','Yemen')
INSERT INTO [dbo].[ISO3166] VALUES('YUG','YU','Yugoslavia')
INSERT INTO [dbo].[ISO3166] VALUES('ZAF','ZA','South Africa')
INSERT INTO [dbo].[ISO3166] VALUES('ZAR','ZR','Zaire')
INSERT INTO [dbo].[ISO3166] VALUES('ZMB','ZM','Zambia')
INSERT INTO [dbo].[ISO3166] VALUES('ZWE','ZW','Zimbabwe')